### ISSUE TITLE
"Led by" should take "office held by head of government" into account

### ISSUE THREAD

**Issue by Abbe98** [govdirectory/website#134]
### Description

Example item affected: https://www.wikidata.org/wiki/Q1002006

**Comment by toukirkhan** [comment]
I guess this one is solved?

**Comment by Ainali** [comment]
No we have not solved this one yet. See https://www.govdirectory.org/south-africa/Q1002006/ for live data.

**Comment by toukirkhan** [comment]
I can definitely solve this please assign me

**Comment by toukirkhan** [comment]
Solved this in PR #243

**Comment by Ainali** [comment]
Hmm, perhaps I was wrong and this one is already solved. Looking at these two that behave as expected:

https://www.wikidata.org/wiki/Q1185115
https://www.govdirectory.org/south-africa/Q1185115/

@Abbe98 Is there something more to do on this one?

**Comment by toukirkhan** [comment]
Please tell me if you have more good first issues.

**Comment by Ainali** [comment]
This is already resolved.

See for example: https://www.govdirectory.org/sweden/Q109010/ where for https://www.wikidata.org/wiki/Q109010#P1313 there is a statement set, and the person who holds that office: https://www.wikidata.org/wiki/Q45023038 shows in our infobox. 

Closing as solved.
